### ISSUE TITLE
Highlighting the current selected tab 

### ISSUE THREAD

**Issue by TauqeerAhmad5201** [TauqeerAhmad5201/react-router#4]
Changing selection background on current item. 

[src/components/Navbar.js](https://github.com/TauqeerAhmad5201/react-router/tree/main/src/components/Navbar.js)

**Comment by Aadish1233** [comment]
hey would u plz merge my pull request

**Comment by TauqeerAhmad5201** [comment]
wait! Let me check 
meanwhile thanks for it.

**Comment by Aadish1233** [comment]
hey did u checked it
